### ISSUE TITLE
How to get the spatial segmentation stroke image?

### ISSUE THREAD

**Issue by FantasyJXF** [LouieYang/stroke-controllable-fast-style-transfer#3]

**Comment by LouieYang** [comment]
You should first manually generate the mask by yourself (use VOC 2012 in README). Then you could get the spatial segmentation result using the mask and three style transferred images of different stroke sizes. We didn't provide end-to-end code for it, but it would be easy once you get the mask and the transferred images.

**Comment by FantasyJXF** [comment]
Thank you
