### ISSUE TITLE
Question about transformer net

### ISSUE THREAD

**Issue by FantasyJXF** [LouieYang/stroke-controllable-fast-style-transfer#5]
This[ line](https://github.com/LouieYang/stroke-controllable-fast-style-transfer/blob/master/netdef.py#L49) .

I'd like to ask why you muliply 150 and plus 125?

Many fast style transfer repos did this

**Comment by LouieYang** [comment]
We followed one of the tensorflow style transfer implementation at that time but I can't find it now. I think it won't influence too much as I have checked some pytorch implementations that don't have this operation.

**Comment by FantasyJXF** [comment]
That line might come from the original Fast Style Transfer repo. The pytorch transformer and TensorFlow has some difference, but it's OK. 

All roads lead to Rome.

**Comment by ycjing** [comment]
I once explored this issue with other researchers. I remember our conclusion is that this procedure is to limit the range for better optimization.

**Comment by FantasyJXF** [comment]
Sounds like math
